name: On Milestone Closed - Build and Release

on:
  milestone:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file ./sources/pom.xml
    - name: Create Milestone Release
      run: |
        MILESTONE_NAME=$(jq --raw-output .milestone.title $GITHUB_EVENT_PATH)
        gh release create $(echo "${MILESTONE_NAME}" | grep -oP '^[a-zA-Z0-9\.]+') ${{ env.FILES }} -n "Release for finished milestone: ${MILESTONE_NAME}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILES: ./sources/qpme.releng.product/target/products/qpme.product-linux.gtk.x86.zip ./sources/qpme.releng.product/target/products/qpme.product-linux.gtk.x86_64.zip ./sources/qpme.releng.product/target/products/qpme.product-win32.win32.x86.zip ./sources/qpme.releng.product/target/products/qpme.product-win32.win32.x86_64.zip ./sources/qpme.releng.product/target/products/qpme.product-macosx.cocoa.x86_64.zip
