name: On Main Commit - Build and Release Latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete latest release
      run: echo $(gh release delete latest -y)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Delete latest tag
      run: echo $(git config user.name github-actions && git config user.email github-actions@github.com && git push --delete origin latest)
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file ./sources/pom.xml
    - name: Create new latest release
      run: gh release create latest ${{ env.FILES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILES: ./sources/qpme.releng.product/target/products/qpme.product-linux.gtk.x86.zip ./sources/qpme.releng.product/target/products/qpme.product-linux.gtk.x86_64.zip ./sources/qpme.releng.product/target/products/qpme.product-win32.win32.x86.zip ./sources/qpme.releng.product/target/products/qpme.product-win32.win32.x86_64.zip ./sources/qpme.releng.product/target/products/qpme.product-macosx.cocoa.x86_64.zip
